import Head from 'next/head'
import Image from 'next/image'
import React, { useContext } from 'react'
import styles from '../../styles/Home.module.css'
import { CartContext } from '../context/index'

export default function Home() {
  const { helloWorld } = useContext(CartContext)

  const hero = {
    name: 'Batman',
    realName: 'Bruce Wayne',
  }
  const { name, realName } = hero

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {helloWorld}
    </div>
  )
}
